### ISSUE TITLE
Issue with Magento Enterprise and the staging module

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/magento2-module-gift-sales-rule-staging#2]
Hi,

In Magento EE 2.3.X (and probably in 2.4.X), in the following case :
A salesrule with a rule_id different (for example 4) of the row_id (for example 1)
In the table smile_gift_salesrule, no row with a rule_id 4

In the table smile_gift_salesrule, the rule_id is linked to the row_id of salesrule. But in the code, we always give to the repository the rule_id of salesrule.
In most of case, it will work, because it exists often a row in salesrule which has the same rule_id and row_id.
But in rare case, it does not exist and cause a fatal error.
The solution is in CE, give the rule_id to the gift salesrule repository, in EE, give the row_id.

**Comment by artttj** [comment]
@PierreLeMaguer 

We have the following exception when we try to save the new Cart Price Rule (EE 2.4.2). Is it related to this problem, what do you think?

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`.`smile_gift_salesrule`, CONSTRAINT `SMILE_GIFT_SALESRULE_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `smile_gift_salesrule` (`rule_id`, `maximum_number_product`, `price_range`) VALUES (?, ?, ?)
```

**Comment by PrigentMatthieu** [comment]
See 1.0.1
