### ISSUE TITLE
JS naming

### ISSUE THREAD

**Issue by krasii** [Smile-SA/magento2-module-gift-sales-rule-staging#4]
Hi.
After click button "Schedule New Update" in console js are absent "Smile_GiftSalesRule/js/form/element/actions-fieldset-staging", "Smile_GiftSalesRule/js/form/element/action-type-staging".
I think, problem in naming in layout, need to replace "Smile_GiftSalesRule" to "Smile_GiftSalesRuleStaging".
Thank you.

**Comment by PrigentMatthieu** [comment]
See 1.0.1
